app/__init__.py
from flask import Flask, render_template
from config import Config
from .api.routes import api
from .site.routes import site
from .authentication.routes import auth

from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from models import db as root_db, login_manager, ma
from flask_cors import CORS
from helpers import JSONEncoder

app = Flask(__name__)
UPLOAD_FOLDER = 'uploads'
app.config['UPLOAD_FOLDER'] = UPLOAD_FOLDER
CORS(app)

app.register_blueprint(site)
app.register_blueprint(auth)
app.register_blueprint(api)

app.json_encoder = JSONEncoder
app.config.from_object(Config)
root_db.init_app(app)
login_manager.init_app(app)
ma.init_app(app)
migrate = Migrate(app, root_db)

app/api/routes.py
from flask import current_app
from werkzeug.utils import secure_filename
import os
from flask import Flask, Blueprint, request, jsonify, render_template
from helpers import token_required
from models import db, User, Image, image_schema, images_schema

#api = Blueprint('api',__name__, url_prefix='/api')
api = Blueprint('api',__name__, url_prefix='/api')

#test API
@api.route('/getdata')
def getdata():
    return {'test': 'testgalleryapi'}

ALLOWED_EXTENSIONS = {'png', 'jpg', 'jpeg', 'gif'}
def allowed_file(filename):
    return '.' in filename and \
           filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS

#Add A Image
@api.route('/images', methods=['POST'])
@token_required
def create_image(current_user_token):
    if 'file' not in request.files:
        return jsonify({'error': 'No file part'})

    file = request.files['file']

    if file.filename == '':
        return jsonify({'error': 'No selected file'})

    if file and allowed_file(file.filename):
        filename = secure_filename(file.filename)
        filepath = os.path.join(current_app.config['UPLOAD_FOLDER'], filename)
        file.save(filepath)

        image_title = request.form.get('image_title', '')
        image_url = filepath  # Now it points to an actual file
        creator_name = request.form.get('creator_name', '')
        no_of_downloads = int(request.form.get('no_of_downloads', 0))
        image_type = request.form.get('image_type', '')
        user_token = current_user_token.token

        # Check if the User Token Exists
        user = User.query.filter_by(token=user_token).first()

        # Insert User if Not Present
        if user is None:
            new_user = User(token=user_token)
            db.session.add(new_user)
            db.session.commit()

        # Insert Image Record
        image = Image(image_title, image_url, creator_name, no_of_downloads, image_type, user_token=user_token)
        db.session.add(image)
        db.session.commit()

        response = image_schema.dump(image)
        return jsonify(response)


#Get List of Images
@api.route('/images', methods = ['GET'])
@token_required
def get_image(current_user_token):
    a_user = current_user_token.token
    images = Image.query.filter_by(user_token = a_user).all()
    response = images_schema.dump(images)
    return jsonify(response)

#get details of sepcific image
@api.route('/images/<id>', methods = ['GET'])
@token_required
def get_single_image(current_user_token, id):    # Currently showing cars of other users as well 
    image = Image.query.get(id)
    response = image_schema.dump(image)
    return jsonify(response)


#Update Image details
@api.route('/images/<id>', methods = ['POST','PUT'])
@token_required
def update_image(current_user_token,id):
    image = Image.query.get(id) 
    image.image_title = request.json['image_title']
    image.image_url = request.json['image_url']
    image.creator_name = request.json['creator_name']
    image.no_of_downloads = request.json['no_of_downloads']
    image.image_type = request.json['image_type']
    image.user_token = current_user_token.token

    db.session.commit()
    response = image_schema.dump(image)
    return jsonify(response)

# Delete Specific Image
@api.route('/images/<id>', methods = ['DELETE'])
@token_required
def delete_image(current_user_token, id):
    image = Image.query.get(id)
    db.session.delete(image)
    db.session.commit()
    response = image_schema.dump(image)
    return jsonify(response)


app/authentication/routes.py
from login_forms import UserLoginForm
from models import User, db, check_password_hash
from flask import Blueprint, render_template, request, redirect, url_for, flash

# imports for flask login 
from flask_login import login_user, logout_user, LoginManager, current_user, login_required

auth = Blueprint('auth', __name__, template_folder='auth_templates')

@auth.route('/signup', methods = ['GET', 'POST'])
def signup():
    form = UserLoginForm()

    try:
        if request.method == 'POST' and form.validate_on_submit():
            email = form.email.data
            password = form.password.data
            print(email, password)

            user = User(email, password = password)

            db.session.add(user)
            db.session.commit()

            flash(f'User account created successfully, {email}', 'User-created')
            return redirect(url_for('site.home'))
    except:
        raise Exception('Invalid form data: Please check your form')
    return render_template('sign_up.html', form=form)


@auth.route('/signin', methods = ['GET', 'POST'])
def signin():
    form = UserLoginForm()
    
    try:
        if request.method == 'POST' and form.validate_on_submit():
            email = form.email.data
            password = form.password.data
            print(email,password)

            logged_user = User.query.filter(User.email == email).first()
            if logged_user and check_password_hash(logged_user.password, password):
                login_user(logged_user)
                flash('Login Successful. Congratulations!!', 'auth-sucess')
                return redirect(url_for('site.profile'))
            else:
                flash('Login Failed.', 'auth-failed')
                return redirect(url_for('auth.signin'))
    except:
        raise Exception('Invalid Form Data: Please Check your Form')
    return render_template('sign_in.html', form=form)

@auth.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('site.home'))

app/site/routes.py
from flask import Blueprint, render_template

site = Blueprint('site', __name__, template_folder='site_templates')

@site.route('/')
def home():
    return render_template('index.html')

@site.route('/images')
def images():
    return render_template('images.html')

@site.route('/profile')
def profile():
    return render_template('profile.html')

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Website to Showcase Image Gallery of my Selected Images"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.1/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
<link rel="stylesheet" href="../static/css/main.css">
<title>Frankie's Sports Images</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-dark navbar-dark py-3 fixed-top">
        <div class="container">
            <a href="#" class="navbar-brand">Frankie's Sports Images</a>
            <button 
                class="navbar-toggler" 
                type="button" 
                data-bs-toggle="collapse" 
                data-bs-target="#navmenu"
            ><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navmenu">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">
                        <a href="{{ url_for('site.home') }}" class="nav-link">Home</a>
                    </li>
                    {% if current_user.is_authenticated %}
                    <li class="nav-item">
                        <a href="{{ url_for('site.profile') }}" class="nav-link">My Profile</a>
                    </li>
                     <li class="nav-item">
                        <a href="{{ url_for('site.images') }}" class="nav-link">Images</a>   
                    </li>
                    <li class="nav-item">
                         <a href="#" class="nav-link">Add Images</a> 
                    </li>
                    <li class="nav-item">
                        <a href="{{ url_for('auth.logout') }}" class="nav-link">Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a href="{{ url_for('auth.signin') }}" class="nav-link">Sign In</a>
                    </li>
                    <li class="nav-item">
                        <a href="{{ url_for('auth.signup') }}" class="nav-link">Sign Up</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
<!-- Mysterious placeholder comment! -->
{% block content %}
{% endblock %}

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.1/js/bootstrap.min.js"></script>
</body>
</html>

app/templates/login_forms.html
<form method="POST">
    {{ form.hidden_tag() }}
    <div class="form-group">
        <fieldset id="email-field">
            {{ form.email.label }}
            {{ form.email(class = 'form-control', placeholder = 'Place Email Here ') }}
        </fieldset>
    </div>

        <fieldset id="pass-field">
            {{ form.password.label }}
            {{ form.password(class = "form-control", placeholder = "Place Password Here ") }}
        </fieldset>

        <!-- Submit button area -->
        {{ form.submit_button(class = "btn btn-primary btn-block mt-2")}}

</form>